config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # API 路由
  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      # article api
      get "/articles" => "articles#index", :as => :articles
      get "/articles/:id" => "articles#show", :as => :article

      # review api
      get "/articles/:article_id/reviews/" => "reviews#index", :as => :reviews
      post "/articles/:article_id/reviews" => "reviews#create", :as => :create_review

      # user 注册/登入/登出 api
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      #user 资料更新 api
      get "/me" => "users#show", :as => :user
      patch "/me" => "users#update", :as => :update_user
    end
  end

  # 后台路由
  namespace :admin do
    resources :articles do
      resources :reviews
    end
  end

end

app/models/article.rb
class Article < ApplicationRecord

  # 上传主图
  mount_uploader :article_cover, ImageUploader

  validates :title, presence: true
  validates :intro, presence: true
  validates :description, presence: true
  validates :article_cover, presence: true

  # 与 user 关系
  belongs_to :user

  # 与 review 关系
  has_many :reviews, dependent: :destroy 

  def date_format(article)
    time_ago_in_words(article.created_at)
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController

  def index
    @articles = Article.all.order("created_at DESC")
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.user = current_user

    if @article.save
      redirect_to admin_articles_path
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to admin_articles_path
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to admin_articles_path
  end


  # ---
  private

  def article_params
    params.require(:article).permit(:title, :intro, :article_cover, :description, :user_id)
  end

end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApiController

  def index
    @articles = Article.all.order("created_at DESC")
    render :json => {
      :article_count => @articles.count,
      :data => @articles.map{ |article|
        {
          :articleId => article.id,
          :title => article.title,
          :intro => article.intro,
          :article_cover => article.article_cover.thumb,
          # :description => article.description,
          :review_count => article.reviews.count,
          :date => article.created_at.to_i,
          # :url => api_v1_article_url(article.id)
        }
      }
    }
  end

  def show
    @article = Article.find(params[:id])
    render :json => {
      :articleId => @article.id,
      :title => @article.title,
      # :article_cover => @article.article_cover.thumb,
      :description => @article.description,
      :review_count => @article.reviews.count,
      :date => @article.created_at.to_i,
      # :url => api_v1_article_url(@article.id)
    }
  end

end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/api/v1/articles_helper.rb
module Api::V1::ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= simple_form_for [:admin, @article] do |f| %>

  <div class="form-group">
    <%= f.input :title, :label => "标题" %>
    <%= f.input :intro, :label => "简介" %>
    <%= f.cktext_area :description, as: :ckeditor, ckeditor: { toolbar: 'mini', language: 'zh-CN', :label => "文章内容" } %>
    <%= f.input :article_cover, as: :file, :label => "主图" %>
    <%= f.submit "提交", :class => "btn btn-sm btn-default", :data => { disable_with: "Submiting..." } %>
  </div>

<% end %>

app/views/admin/articles/edit.html.erb
<div>

  <h2>编辑文章</h2>

  <%= render "form" %>

</div>

app/views/admin/articles/index.html.erb
<div>

  <div>
    <%= link_to("新建文章", new_admin_article_path, :class => "btn btn-default pull-right" )%>
  </div>

  <h2>文章列表</h2>

  <table class="table table-boldered">
    <thead>
      <tr>
        <th>ID</th>
        <th>标题</th>
        <th>简介</th>
        <th>主图</th>
        <th>修改时间</th>
        <th>管理</th>
        <th>回复</th>
      </tr>
    </thead>
    <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td><%= article.id %></td>
          <td><%= article.title %></td>
          <td><%= article.intro %></td>
          <td><%= image_tag(article.article_cover.thumb.url) %></td>
          <td><%= article.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
          <td>
            <%= link_to("编辑", edit_admin_article_path(article), :class => "btn btn-xs btn-default" )%>
            <%= link_to("删除", admin_article_path(article), method: :delete, :class => "btn btn-xs btn-default", data: { confirm: "确定删除" }) %>
          </td>
          <td>
            <%= link_to("回复", admin_article_reviews_path(article), :class => "btn btn-xs btn-default") %>
            <span class="pull-right"><%= article.reviews.count %></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/articles/new.html.erb
<div>

  <h2>新建文章</h2>

  <%= render "form" %>

</div>