config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # API 路由
  namespace :api, :defaults => { :format => :json } do
    namespace :v1 do
      # article api
      get "/articles" => "articles#index", :as => :articles
      get "/articles/:id" => "articles#show", :as => :article

      # review api
      get "/articles/:article_id/reviews/" => "reviews#index", :as => :reviews
      post "/articles/:article_id/reviews" => "reviews#create", :as => :create_review

      # user 注册/登入/登出 api
      post "/signup" => "auth#signup"
      post "/login" => "auth#login"
      post "/logout" => "auth#logout"

      #user 资料更新 api
      get "/me" => "users#show", :as => :user
      patch "/me" => "users#update", :as => :update_user
    end
  end

  # 后台路由
  namespace :admin do
    resources :articles do
      resources :reviews
    end
  end

end

app/controllers/admin/reviews_controller.rb
class Admin::ReviewsController < AdminController

  def index
    @article = Article.find(params[:article_id])
    @reviews = @article.reviews.order("created_at DESC")
    @review = Review.new
  end

  def new
    @article = Article.find(params[:article_id])
    @review = Review.new
  end

  def create
    @article = Article.find(params[:article_id])
    @review = Review.new(review_params)
    @review.article = @article
    @review.user = current_user

    if @review.save
      redirect_to admin_article_reviews_path(@article)
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:article_id])
    @review = Review.find(params[:id])
  end

  def update
    @article = Article.find(params[:article_id])
    @review = Review.find(params[:id])

    if @review.update(review_params)
      redirect_to admin_article_reviews_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:article_id])
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to admin_article_reviews_path(@article)
  end


  private

  def review_params
    params.require(:review).permit(:content)
  end

end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApiController

  # 允许未登录匿名评论
  # before_action :authenticate_user!, :only => [:create]

  def index
    @article = Article.find(params[:article_id])
    @reviews = @article.reviews.order("created_at DESC")
    render :json => {
      :review_count => @reviews.count,
      :data => @reviews.map{ |review|
        {
          :articleId => @article.id,
          :reviewId => review.id,
          :content => review.content,
          :user_name => review.user.try(:display_name),
          :user_avatar => review.user.try(:avatar).try(:thumb),
          :date => review.created_at.to_i,
          # :url => api_v1_reviews_path(@article)
        }
      }
    }
  end

  def create
    @article = Article.find(params[:article_id])
    @review = Review.new(
      :content => params[:content]
    )

    @review.article = @article
    @review.user = current_user

    if @review.save
      render :json => {
        :article_id => @article.id,
        :user_id => @review.user.try(:id),
        :content => @review.content
      }
    else
      render :json => {
        :message => "回复失败",
        :errors => @review.errors
      }, :status => 400
    end
  end

end

app/helpers/admin/reviews_helper.rb
module Admin::ReviewsHelper
end

app/helpers/api/v1/reviews_helper.rb
module Api::V1::ReviewsHelper
end

app/views/admin/reviews/edit.html.erb
<h3>编辑回复内容:</h3>

<div>
  <%= simple_form_for [:admin, @article, @review] do |f|%>

    <div class="form-group">
      <%= f.input :content, :label => "输入回复" %>
      <%= f.submit "提交", :class => "btn btn-sm btn-default", :data => { disable_with: "Submiting..." } %>
    </div>

  <% end %>
</div>

app/views/admin/reviews/index.html.erb
<h3>Article: <%= @article.title %></h3>

<div>
  <%= simple_form_for [:admin, @article, @review] do |f|%>

    <div class="form-group">
      <%= f.input :content, :label => "输入回复" %>
      <%= f.submit "提交", :class => "btn btn-sm btn-default", :data => { disable_with: "Submiting..." } %>
    </div>

  <% end %>
</div>

<table class="table table-boldered">
  <thead>
    <tr>
      <th> ID </th>
      <th> 回复内容</th>
      <th> 回复人 </th>
      <th> 时间 </th>
      <th> 操作 </th>
    </tr>
  </thead>
  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.id %></td>
        <td><%= review.content %></td>
        <td>
          <%= review.user.try(:display_name) %> </br>
          Token: <%= review.user.try(:authentication_token) %>
        </td>
        <td><%= review.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
        <td>
          <%= link_to("编辑", edit_admin_article_review_path(@article, review), :class => "btn btn-xs btn-default" )%>
          <%= link_to("删除", admin_article_review_path(@article, review), method: :delete, :class => "btn btn-xs btn-default", data: { confirm: "确定删除" }) %>
        </td>
      </tr>
    <% end %>
  </tbody>

</table>